# Generated by Django 5.2.11 on 2026-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('work_duration', models.CharField(max_length=100)),
                ('work_detail', models.TextField(default='None', max_length=500)),
            ],
        ),
    ]
