# Generated by Django 5.2.11 on 2026-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('techstack', models.CharField(max_length=2000)),
                ('live', models.URLField(blank=True)),
                ('codebase', models.URLField(blank=True)),
                ('duration', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
                ('project_description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
