# Generated by Django 5.2.11 on 2026-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skiller', models.CharField(default="Karan's Skills", max_length=100)),
                ('ai', models.CharField(max_length=300)),
                ('frontend', models.CharField(max_length=300)),
                ('backend', models.CharField(max_length=300)),
                ('tools', models.CharField(max_length=300)),
                ('deployment', models.CharField(max_length=300)),
            ],
        ),
    ]
